# Generated by Django 5.0 on 2024-05-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskserver', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dependencies',
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
